Fixed bug in query 14 comparison method.
Would get:

java.lang.IllegalArgumentException: Comparison method violates its general contract!

on:

query14 32985349165883 19791209335567

Because the comparison method was not implementing a transitive
comparison.

Removed autoboxing in comparison methods in general to solve this
problem and potentially any others.